#! /bin/sh

# Restart hotkey daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# Restart authentication agent for polkit
pgrep -x lxqt-policykit- > /dev/null || lxqt-policykit-agent &

# Restart unclutter for auto hiding cursor when usused
pgrep -x unclutter > /dev/null || unclutter &

# Disable mouse acceleration on all pointer devices
for id in $(xinput list | grep "pointer" | cut -d '=' -f 2 | cut -f 1); do xinput --set-prop $id 'libinput Accel Profile Enabled' 0, 1; done &

# Display configuration and bspc workspace, dependent on device
if [[ $(hostnamectl hostname) == 'arch' && $(hostnamectl chassis) == 'desktop' ]]; then
	xrandr --output HDMI-0 --primary --mode 1920x1080 --rate 144 &
	xrandr --output DP-3 --right-of HDMI-0 --mode 1920x1080 --rate 60 &
	bspc monitor HDMI-0 -d I II III IV V
	bspc monitor DP-3 -d VI VII VIII IX X
elif [[ $(hostnamectl hostname) == 'arch' && $(hostnamectl chassis) == 'laptop' ]]; then
	xrandr --output eDP1 --primary --mode 1920x1080 --rate 60 &
	bspc monitor -d I II III IV V VI VII VIII IX X
fi

# bspc global
bspc config focus_follows_pointer true

# bspc apperance
bspc config top_padding 32
bspc config window_gap 10 #12
bspc config split_ratio 0.52

# bspc border
bspc config border_width 2
bspc config normal_border_color "#4c566a"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#327bd1"
bspc config presel_feedback_color "#327bd1"
bspc config urgent_border_color "#dd2727"

# bspc floating windows
# super +
#	mouse1 move
#	middle resize from side
#	mouse2 resize from corner
bspc config pointer_action1 move
bspc config pointer_action2 resize_size
bspc config pointer_action3 resize_corner

# bspc rules
bspc rule -a mpv state=floating
bspc rule -a Zathura state=tiled

# Autostart
picom --experimental-backends &	# Compositor
dunst &				# Notification daemon
fcitx &				# Input method framework
~/.config/polybar/launch.sh &	# Polybar
~/.fehbg & # Wallpaper restore

# Set default cursor to left pointer
# https://wiki.archlinux.org/index.php/Cursor_themes#Change_X_shaped_default_cursor
xsetroot -cursor_name left_ptr &
